name: CI to Docker Hub
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - name: Check Out Repo
    uses: actions/checkout@v2
  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secret.DOCKER_HUB_USERNAME }}
      password: ${{ secret.DOCKER_ACCESS_TOKEN }}
  - name: Set up Docker Buildx
    id: bulidx
    uses: docker/setup-build-action@v1
  - name: Build and push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      context: ./
      push: true
      tags: ${{ secret.DOCKER_HUB_USERNAME }}/simplewhale:lastest
  - name: Image digest
    run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      
